### ISSUE TITLE
Include PR create date in the output

### ISSUE THREAD

**Issue by slmingol** [Jmainguy/ghreport#13]
Would be a nice add to this if it included the list of the PRs open in a given repo along with the date it was created.

**Comment by Jmainguy** [comment]
let me know if this works for you.

**Comment by slmingol** [comment]
Cool it works!

**Comment by Jmainguy** [comment]
yeah havent cut a new release yet, wanted to get the customer happy (you), will see about formatting it similar to that

**Comment by Jmainguy** [comment]
Released in https://github.com/Jmainguy/ghreport/releases/tag/v0.1.0
