### ISSUE TITLE
Show the owner of the PR in output

### ISSUE THREAD

**Issue by slmingol** [Jmainguy/ghreport#29]
Would it be possible to add another column to the output or a switch to enable/disable a column showing the name of the user that created the PR?

**Comment by Jmainguy** [comment]
Checkout https://github.com/Jmainguy/ghreport/releases/tag/v0.2.0

[jmainguy@fedora ghreport]$ ./ghreport 
https://github.com/Jmainguy/stockop/pull/9:  author: renovate  createdAt 2023-04-07 01:10:22 +0000 UTC

**Comment by slmingol** [comment]
Checked out release and the commits fixed this ask. Feel free to close I consider this ask done from my perspective. TY for fixing it.
